about:
  home: http://metacpan.org/pod/Config-Any
  license: perl_5
  summary: Load configuration from different file formats, transparently
build:
  number: 5
  run_exports:
  - null
extra:
  additional-platforms:
  - osx-arm64
  - linux-aarch64
package:
  name: perl-config-any
  version: 0.33
requirements:
  build:
  - make
  - null
  host:
  - perl >=5.32.1
  - perl-app-cpanminus
  - perl-extutils-makemaker
  run:
  - perl >=5.32.1
  - perl-app-cpanminus
source:
  sha256: c0668eb5f2cd355bf20557f04dc18a25474b7a0bcfa79562e3165d9a3c789333
  url: https://cpan.metacpan.org/authors/id/H/HA/HAARG/Config-Any-0.33.tar.gz
test:
  imports:
  - Config::Any
  - Config::Any::Base
  - Config::Any::General
  - Config::Any::INI
  - Config::Any::JSON
  - Config::Any::Perl
  - Config::Any::XML
  - Config::Any::YAML
