 
name: bioconda import

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 5'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        repository: bioconda/bioconda-recipes
        path: bioconda
    - uses: actions/checkout@v2
      with:
        path: content
    - name: import bioconda tools
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo pip3 install virtualenv
        virtualenv -p python3 venv
        . venv/bin/activate	
        pip3 install setuptools wheel jinja2 pyyaml
        python3 ${{ github.workspace }}/content/scripts/bioconda-import/bioconda_importer.py ${{ github.workspace }}/content/data/ ${{ github.workspace }}/bioconda/recipes/
        cd ${{ github.workspace }}/content/data
        git config --local user.email "tpe-bot@github.com"
        git config --local user.name "Tools Platform Ecosystem bot"
        git add .
        git status

        if git commit -m "bioconda import on $(date)"; then
          git checkout -b bioconda_import${{ github.run_id }}
          git push --set-upstream origin "bioconda_import${{ github.run_id }}"
          hub pull-request -m "bioconda import on $(date)"
          echo "successfully created new data"
        else
            echo "nothing new to add, exiting"
        fi
