name: import bio.tools

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  import-biotools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bio-tools/content-ecosystem-utils/biotools-import@main
      with:
        repo-user: ${{ secrets.GITHUB_USER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
