name: analize how many biotools have change on pullrequest

on:
  pull_request:

jobs:
  analize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: geertvdc/setup-hub@master
    - name: analize biotools difference
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt install python3-pip
        sudo apt install python3-setuptools
        pip3 install gitpython
        pr_comment=$(python3 scripts/biotools-pullrequest-bot/biotools_pullrequest_analizer.py $GITHUB_WORKSPACE master ${{ github.head_ref }})
        echo $pr_comment
    - uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: $pr_comment
