name: analize how many biotools have change on pullrequest

on:
  pull_request:

jobs:
  analize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: geertvdc/setup-hub@master
    - name: analize biotools difference
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt install python3-pip
        sudo apt install python3-setuptools git
        pip3 install gitpython
        git remote add biotools-content${{ github.run_id }} https://github.com/bio-tools/content.git
        git fetch biotools-content${{ github.run_id }}
        git fetch origin
        pr_comment=$(python3 scripts/biotools-pullrequest-bot/biotools_pullrequest_analizer.py $GITHUB_WORKSPACE biotools-content${{ github.run_id }}/master ${{ github.head_ref }})
        echo $pr_comment
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          **Hello**
          üåè
          !
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-repeats: false
