name: launch a test bio.tools server and perform import tests

on:
  workflow_dispatch:

jobs:

  runbiotools:

    runs-on: ubuntu-latest

    steps:
    - name: checkout contents registry
      if: github.actor == github.event.repository.owner.login
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: ./content
    - name: checkout bio.tools registry
      uses: actions/checkout@v2
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'bio-tools/biotoolsRegistry'
        path: ./biotoolsRegistry
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
    - name: Add dummy email backend to django settings
      working-directory: ./biotoolsRegistry
      run: |
        echo "EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'" >> backend/elixirapp/settings.py
    - name: build docker containers for bio.tools registry
      working-directory: ./biotoolsRegistry
      run: |
        docker-compose build
    - name: start docker containers for bio.tools registry
      working-directory: ./biotoolsRegistry
      run: |
          docker-compose up -d
    - name: debug
      working-directory: ./content
      run: |
          ls
    - name: copy wait for mysql script
      working-directory: ./content
      run: |
          docker cp scripts/runbiotools/wait_mysql.sh biotools-mysql:/root
    - name: chmod to executable wait for mysql script
      working-directory: content
      run: |
          docker exec biotools-mysql chmod +x /root/wait_mysql.sh
    - name: execute wait for mysql script
      working-directory: content
      run: |
          docker exec biotools-mysql /root/wait_mysql.sh
    - name: test that bio.tools registry is up and running
      run: |
        wget --spider http://localhost:8000
    - name: list running containers
      run: |
        docker ps -a
    - name: test that bio.tools registry database is up and running through the HTTP API...
      run: |
        wget --spider http://localhost:8000/api/t || :
    - name: copy database init SQL
      working-directory: biotoolsRegistry
      run: |
          docker cp initial_db.sql biotools-mysql:/root
    #- name: copy "modified" database init script
    #  working-directory: content
    #  run: |
    #      docker cp scripts/runbiotools/load_initial_db.sh biotools-mysql:/root
    - name: load DB with initial data
      working-directory: biotoolsRegistry
      run: |
        docker exec biotools-mysql mysql -h mysql -P 3306 --protocol tcp --user=elixir --password=123 elixir < initial_db.sql
    - name: create and run django migrations
      run: |
        docker exec biotools-backend python manage.py makemigrations
        docker exec biotools-backend python manage.py migrate
    - name: purge and reload elasticsearch
      run: |
        docker exec biotools-backend python manage.py es_purge
        docker exec biotools-backend python manage.py es_regenerate
    - name: test that bio.tools registry is up and running
      run: |
        wget --spider http://localhost:8000
    - name: create user to upload data to server
      run: |
        curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -d '{"username":"uploadbot", "password1":"botbotbot", "password2":"botbotbot", "email":"uploadbot@example.com"}' "http://localhost:8000/api/rest-auth/registration/"
